<template>
<div>
    <div class="model-inform">
        <div class="title">职业分类表</div>
        <div class="textarea">
            <div class="modal-content" data-content="modal">
                <table bordercolor="black" border="1" align="center" cellspacing="0" cellpadding="0" class="blyw-table">
                    <tbody><tr>
                        <td colspan="2" style="text-align:center">职业分类表（1-4类）</td>
                    </tr>
                    <tr>
                        <td width="140">中分类</td>
                        <td>小分类</td>
                    </tr>
                    <tr>
                        <td>/</td>
                        <td>16岁以下儿童（不含学龄前儿童）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>无业人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>离退休人员（无兼职）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>自由职业者内勤（不可归于本表其他类别者）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>自由职业者外勤（不可归于本表其他类别者）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>家庭主妇</td>
                    </tr>
                    <tr>
                        <td>机关团体公司</td>
                        <td>内勤人员(不从事危险工作)</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>外勤人员(不属于本表下列职业分类所列者)</td>
                    </tr>
                    <tr>
                        <td>工厂</td>
                        <td>负责人（不亲自作业）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>厂长（不亲自作业）</td>
                    </tr>
                    <tr>
                        <td>农业</td>
                        <td>农场经营者（不亲自作业）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>农民</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>长短工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>果农</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>苗圃栽培人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>花圃栽培人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>饲养家禽家畜人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>农业技师、指导员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>农业机械之操作及修理人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>农具商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>糖场技工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>昆虫（蜜蜂）饲养人员</td>
                    </tr>
                    <tr>
                        <td>畜牧业</td>
                        <td>畜牧场经营者（不亲自作业）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>畜牧工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>兽医</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>动物养殖人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>驯犬人员</td>
                    </tr>
                    <tr>
                        <td>内陆渔业</td>
                        <td>渔场经营者（不亲自作业）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>渔场经营者（亲自作业）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>养殖工人（内陆）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>热带鱼养殖人、水族馆经营者</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>捕鱼人（内陆）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>水产实验人员（室内）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>水产加工工人</td>
                    </tr>
                    <tr>
                        <td>森林砍伐业</td>
                        <td>领班</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>监工</td>
                    </tr>
                    <tr>
                        <td>木材加工业</td>
                        <td>木材工厂现场之职员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>分级员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>检查员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>标记员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>磅秤员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>防腐剂工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>木材储藏槽工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>吊车操作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>合板制造工人</td>
                    </tr>
                    <tr>
                        <td>造林业</td>
                        <td>领班</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>山地造林人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>山林管理人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>平地育苗人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>实验室育苗栽培人员</td>
                    </tr>
                    <tr>
                        <td>农林牧渔服务业</td>
                        <td>技术服务咨询人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>联合收割机驾驶员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>农用运输车驾驶员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>农用机械操作及修理人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>能源设备安装、调试、检修人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>沼气生产管理人员</td>
                    </tr>
                    <tr>
                        <td>坑外作业</td>
                        <td>经营者（不到现场者）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>经营者（现场监督者）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>经理</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>矿业工程师、技师、领班</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>工矿安全人员</td>
                    </tr>
                    <tr>
                        <td>煤炭开采和洗选业</td>
                        <td>煤炭开采和洗选业管理人员</td>
                    </tr>
                    <tr>
                        <td>金属矿采选业</td>
                        <td>金属矿采选管理人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>金属矿技术人员</td>
                    </tr>
                    <tr>
                        <td>其他矿采选业</td>
                        <td>其他矿采选业管理人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>其他矿采选业技术人员</td>
                    </tr>
                    <tr>
                        <td>石油和天然气开采业</td>
                        <td>油气开采管理人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>油气开采技术人员</td>
                    </tr>
                    <tr>
                        <td>陆运</td>
                        <td>出租车企业、物流企业负责人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>外务员（无驾照人员）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>内勤工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>自用小客车司机</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>自用大客车司机</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>出租车、救护车司机</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>游览车司机及服务员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>客运车司机及服务员（市区内）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>客运车司机及服务员（中长途、高速路段）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>小型客货两用车司机</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>自用货车司机、随车工人、搬家工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>人力三轮车工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>柜台售票员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>客运车稽核人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>搬运工人、装卸工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>货柜车司机、随车人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>缆车操作员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>公路收费及监控人员</td>
                    </tr>
                    <tr>
                        <td>铁路</td>
                        <td>站长</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>票房工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>播音员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>一般内勤人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>车站检票员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>服务台人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>月台上工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>车站治安巡视人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>行李搬运工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>车站清洁工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>随车人员（技术人员除外）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>驾驶员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>燃料填充员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>机工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>电工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>修护厂厂长</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>修护厂一般内勤人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>修护厂工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>修护厂技工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>修路工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>铁路维护员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>平交道看守人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>铁路货运领班</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>铁路货运搬运工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>铁路通信工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>铁路押运员</td>
                    </tr>
                    <tr>
                        <td>航运</td>
                        <td>Aa客货轮（内河）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>轮机长</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>高级船员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>大副</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>二副</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>三副</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>大管轮</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>二管轮</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>三管轮</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>报务员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>事务长</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>医务人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>Ab客货轮（沿海）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>轮机长</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>高级船员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>大副</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>二副</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>三副</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>大管轮</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>二管轮</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>三管轮</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>报务员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>事务长</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>医务人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>C港口作业</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>码头工人及领班（船上作业）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>码头工人及领班（陆上作业）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>堆高机操作员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>仓库管理人、理货员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领航员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>引水员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>关务人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>稽查人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>缉私人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>D</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>拖船驾驶员及工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>渡船驾驶员及工作人员</td>
                    </tr>
                    <tr>
                        <td>空运</td>
                        <td>A航空站</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>站长</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>播音员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>服务台人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>一般内勤人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>塔台工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>管务人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>检查人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>运务人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>缉私人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>站内清洁工人(航空大厦内)</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>机场内交通车司机</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>行李货运搬运工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>加添燃料人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>飞机洗刷人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>清洁工（站外，航空大厦外）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>跑道维护工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>机械员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>飞机维护人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>B航空公司</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>办事处人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>票务人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>机场柜台工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>清洁工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>C航空货运</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>一般内勤人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>外务员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>报关人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>理货员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>D空勤人员</td>
                    </tr>
                    <tr>
                        <td>旅游业</td>
                        <td>一般内勤人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>外务员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>导游、领队</td>
                    </tr>
                    <tr>
                        <td>旅馆业</td>
                        <td>负责人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>一般内勤工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>外务员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>收帐员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>技工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>注：餐饮部工作人员比照餐饮业</td>
                    </tr>
                    <tr>
                        <td>餐饮业</td>
                        <td>经理人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>一般内勤工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>柜台人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>收帐员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>采购人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>厨师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>服务人员</td>
                    </tr>
                    <tr>
                        <td>建筑公司（土木工程）</td>
                        <td>建筑设计人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>制图员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>内勤工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>测量员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>工程监理</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>建筑公司负责人、业务员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>引导参观工地之服务人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>模板工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>木匠</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>泥水匠</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>混凝土混合机操作员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>油漆工、喷漆工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>水电工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>建筑工程车辆驾驶员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>承包商（土木建筑）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>磨石工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>洗石工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>石棉瓦或浪板安装工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>排水工程人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>防水工程人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>砌筑、砌砖工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>混凝土工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>混凝土制品模具工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>混凝土搅拌机械操作工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>装饰装修工（室内）（基础装修至毛坯）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>室内成套设施装饰工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>古建筑结构施工工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>古建筑装饰工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>房屋维修工人（室内）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>轻钢彩板安装和维修人员</td>
                    </tr>
                    <tr>
                        <td>铁路道路铺设</td>
                        <td>工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>现场勘测人员（非山区）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>铺设工人（平地）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>管道铺设及维护工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>铁道线路工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>枕木处理工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>铁路平交道看守人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>铁路修护厂技工</td>
                    </tr>
                    <tr>
                        <td>造修船业</td>
                        <td>工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>注：造修游艇人员职业类别各减一级</td>
                    </tr>
                    <tr>
                        <td>电梯、升降机</td>
                        <td>安装工人（非高空作业）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>修理及维护工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>操作员（不包括矿场使用者）</td>
                    </tr>
                    <tr>
                        <td>装璜业</td>
                        <td>设计制图人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>地毯之装设人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>住宅室内装璜人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>承包商、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>PVC材质制造、装修工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>木工、油漆工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>机械设备安装工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>电气设备安装工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>管工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>防火系统、警报器安装人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>地质探测员（平地）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>工地看守员（平地）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>中小型施工机械操作工</td>
                    </tr>
                    <tr>
                        <td>测绘工程</td>
                        <td>大地、工程测量工程技术人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>摄影测量与遥感工程技术人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>地图制图与印刷工程技术人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>海洋测绘工程技术人员（非海上作业）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>地质勘探工程技术人员</td>
                    </tr>
                    <tr>
                        <td>冶金业</td>
                        <td>负责人（不亲自作业）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>品管人员</td>
                    </tr>
                    <tr>
                        <td>机械制造业</td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>技工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>板金工、钳工、丸铁工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>装配工、品管人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>车床工（全自动）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>电镀工</td>
                    </tr>
                    <tr>
                        <td>电子业</td>
                        <td>工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>装配工、操作自动I.C制作员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>修理工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>包装工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>制造工</td>
                    </tr>
                    <tr>
                        <td>电机业</td>
                        <td>工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>空气调节器之装修人员（不需空中作业）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>装配修理工、冷冻修理工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>家电用品维修人员</td>
                    </tr>
                    <tr>
                        <td>塑胶橡胶业</td>
                        <td>工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>一般工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>塑胶射出成型工人（自动）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>塑胶射出成型工人（其他）</td>
                    </tr>
                    <tr>
                        <td>水泥业（包括水泥、石膏、石灰）</td>
                        <td>工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>陶瓷、木炭、砖块制造工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>陶瓷彩绘工</td>
                    </tr>
                    <tr>
                        <td>化学原料业</td>
                        <td>工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>一般工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>电池制造（技师）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>电池制造（工人）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>药品制造工、品管员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>化学实验师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>化学原料品管员</td>
                    </tr>
                    <tr>
                        <td>汽车、机车、自行车制造、修理业</td>
                        <td>工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>制造工人（汽、机车）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>制造工人（自行车）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>修理、保养工人（汽、机车）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>修理、保养工人（自行车）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>试车人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>品管人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>板金工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>装潢工、喷漆工、冷气装配员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>烤漆工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>轮胎装配修理</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>汽车玻璃装配工</td>
                    </tr>
                    <tr>
                        <td>纺织及成衣业</td>
                        <td>工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>设计师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>缝纫工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>制造工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>皮革加工工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>染整工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>行政工作人员（经理、文书）</td>
                    </tr>
                    <tr>
                        <td>造纸工业</td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>造纸厂工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>纸箱制造业工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>品管人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>轧纸盒工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>纸盒粘贴工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>裁纸工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>纸箱包装工人</td>
                    </tr>
                    <tr>
                        <td>家具制造</td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>木制家具修理工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>金属家具修理工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>品管人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>家具油漆工（喷漆、烤漆）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>藤制家具制造修理工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>木材及家具检验工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>行政人员（经理、文书）</td>
                    </tr>
                    <tr>
                        <td>手工艺品业</td>
                        <td>竹木制手工艺品之加工工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>竹木制手工艺品之雕刻工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>金属手工艺品之加工工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>金属手工艺品之雕刻工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>布类纸品工艺品之加工工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>珠宝首饰加工工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>皮革手工艺品加工工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>矿石手工艺品加工人员</td>
                    </tr>
                    <tr>
                        <td>陶器工业</td>
                        <td>雕塑工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>烧陶工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>手拉坯工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>陶艺加工人员</td>
                    </tr>
                    <tr>
                        <td>电线电缆业</td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>工人</td>
                    </tr>
                    <tr>
                        <td>食品饮料制造业</td>
                        <td>冰块制造</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>制造工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>碾米厂操作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>装罐工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>装瓶工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>利乐包装工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>其他包装工人</td>
                    </tr>
                    <tr>
                        <td>烟草、香烟制造</td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>行政人员（经理、主任、文员）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>熟练工人、机器操作员</td>
                    </tr>
                    <tr>
                        <td>家电制造业</td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>一般制造工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>装配工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>包装工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>车床工（全自动）</td>
                    </tr>
                    <tr>
                        <td>食品加工业</td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>装罐工人</td>
                    </tr>
                    <tr>
                        <td>玻璃制造</td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>监工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>玻璃艺术品制造工</td>
                    </tr>
                    <tr>
                        <td>金属制品业</td>
                        <td>技师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>领班、监工</td>
                    </tr>
                    <tr>
                        <td>新闻业、杂志业</td>
                        <td>内勤人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>外勤人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>摄影记者</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>推销员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>排版工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>装订工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>印刷工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>送货员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>送报员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>制版工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>裁纸工人</td>
                    </tr>
                    <tr>
                        <td>广告业</td>
                        <td>一般内勤人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>业务员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>广告招牌绘制人员（地面工作）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>广告影片拍摄、录制人员</td>
                    </tr>
                    <tr>
                        <td>医院</td>
                        <td>一般医务行政人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>一般医师及护士</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>精神病科医师、看护及护士</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>医院炊事</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>杂工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>清洁工</td>
                    </tr>
                    <tr>
                        <td>保健人员</td>
                        <td>病理检查员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>分析员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>放射线之技术人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>放射线之修护人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>助产士、齿模工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>跌打损伤治疗人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>监狱、看守所医生、护理人员</td>
                    </tr>
                    <tr>
                        <td>电影、电视业</td>
                        <td>制片人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>影片商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>编剧</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>一般演员（导演）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>化妆师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>场记</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>摄影工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>灯光及音响效果工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>冲片工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>洗片工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>电视记者</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>机械工、电工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>布景搭设人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>电影院售票员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>电影院放映、服务人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>武术指导</td>
                    </tr>
                    <tr>
                        <td>高尔夫球场</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>球场保养工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>维护工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>球童</td>
                    </tr>
                    <tr>
                        <td>保龄球馆</td>
                        <td>计分员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>柜台人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>机械保护员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>清洁工人</td>
                    </tr>
                    <tr>
                        <td>撞球场</td>
                        <td>负责人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>计分员</td>
                    </tr>
                    <tr>
                        <td>游泳池</td>
                        <td>负责人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>管理员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>售票员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>救生员</td>
                    </tr>
                    <tr>
                        <td>海水浴场</td>
                        <td>负责人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>管理员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>售票员</td>
                    </tr>
                    <tr>
                        <td>其他游乐园（包括动物园）</td>
                        <td>负责人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>售票员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>电动玩具操作员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>一般清洁工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>兽栏清洁工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>水电机械工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>饲养人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>兽医（动物园）</td>
                    </tr>
                    <tr>
                        <td>艺术及演艺人员</td>
                        <td>作曲人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>编曲人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>演奏人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>绘画人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>舞蹈演艺人员、歌星</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>雕塑人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>戏剧演员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>巡回演出戏剧团体人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>作家</td>
                    </tr>
                    <tr>
                        <td>娱乐场所</td>
                        <td>咖啡厅工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>茶室工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>酒家工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>夜总会工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>舞厅工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>歌厅工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>酒吧工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>负责人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>KTV、MTV、PTV工作人员</td>
                    </tr>
                    <tr>
                        <td>教育机构</td>
                        <td>教师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>学生</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>校工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>军训教官、体育教师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>杂技教师、学生</td>
                    </tr>
                    <tr>
                        <td>其他</td>
                        <td>负责人（出版商、书店、文具）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>店员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>外务员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>送货员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>图书馆工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>博物馆工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>汽车驾驶训练班教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>各项运动教练</td>
                    </tr>
                    <tr>
                        <td>宗教人士</td>
                        <td>寺庙及教堂管理人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>宗教团体工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>僧尼、道士及传教人员</td>
                    </tr>
                    <tr>
                        <td>邮政</td>
                        <td>内勤人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>外勤邮务人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>包裹搬运人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>快递公司外务</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>快递公司司机</td>
                    </tr>
                    <tr>
                        <td>电信及电力</td>
                        <td>内勤人员及负责设计工作之电机工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>抄表员、收费员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>电信及电力装置维护修理工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>电信及电力工程设施之架设人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>水力发电工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>火力发电工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>核电站行政人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>核电站工作人员</td>
                    </tr>
                    <tr>
                        <td>自来水（水利）</td>
                        <td>工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>水坝、水库管理人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>水利工程设施人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>自来水装修人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>抄表员、收费员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>自来水厂水质分析员（实地）</td>
                    </tr>
                    <tr>
                        <td>燃气</td>
                        <td>工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>管线装修工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>收费员、抄表员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>检察员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>燃气器具制造工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>燃气储气槽、分装厂工作人员</td>
                    </tr>
                    <tr>
                        <td>买卖</td>
                        <td>厨具商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>陶瓷器商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>古董商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>花卉商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>米商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>杂货商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>玻璃商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>果菜商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>石材商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>建材商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>铁材商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>木材商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>五金商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>电器商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>水电卫生器材商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>机车买卖商（不含修理）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>汽车买卖商（不含修理）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>车辆器材商（不含矿物油）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>矿物油、香烛买卖商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>眼镜商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>食品商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>文具商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>布商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>服饰买卖商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>鱼贩</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>肉贩</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>屠宰</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>屠牛</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>药品买卖商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>医疗器械仪器商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>化学原料商、农药买卖商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>手工艺品买卖商</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>银楼珠宝、当铺负责人及工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>燃气器具店</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>负责人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>店员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>送货员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>装饰工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>液化燃气零售店</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>负责人及工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>送货员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>售货商</td>
                    </tr>
                    <tr>
                        <td>银行、保险、信托</td>
                        <td>一般内勤人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>外务员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>收费员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>调查员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>征信人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>现金运送车司机、点钞人员、押送员</td>
                    </tr>
                    <tr>
                        <td>自由业</td>
                        <td>律师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>会计师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>代书（内勤）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>经纪人（内勤）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>土地房屋买卖介绍人</td>
                    </tr>
                    <tr>
                        <td>其他</td>
                        <td>公证行外务员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>报关行外务员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>理发师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>美容师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>钟表匠</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>鞋匠、伞匠</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>洗衣店工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>勘查师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>警卫人员（工厂、公司大楼）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>大楼管理员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>摄影师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>道路清洁工、垃圾车司机及随车工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>下水道清洁工</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>清洁打蜡工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>收费站、停车场收费人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>加油站工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>地磅场工作人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>洗车工人</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>桑拿业工作人员</td>
                    </tr>
                    <tr>
                        <td>家庭管理</td>
                        <td>家政服务员（小时工）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>保姆（全日制）</td>
                    </tr>
                    <tr>
                        <td>警务人员</td>
                        <td>警务行政及内勤人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>警察（负有巡逻任务者）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>监狱看守所管理人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>交通警察</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>军校、警校学生</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>港口、机场警卫及安全人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>治安调查人员</td>
                    </tr>
                    <tr>
                        <td>检察审判人员</td>
                        <td>犯罪调查处理人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>法官、检察官、书记员、翻译员</td>
                    </tr>
                    <tr>
                        <td>其他执法、治安及特种工作人员</td>
                        <td>港口机场警卫及安全人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>工商、税务、海关、城管等特定国家行政执法人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>缉私人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>违禁品检查员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>保安人员（办公楼、物业）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>保安人员（工厂、银行）</td>
                    </tr>
                    <tr>
                        <td>军人</td>
                        <td>行政及内勤人员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>一般军人(空中、海中服役者拒保)</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>宪兵</td>
                    </tr>
                    <tr>
                        <td>IT业（软、硬件开发制作）</td>
                        <td>维护工程师</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>系统工程师（软、硬件）</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>销售人员</td>
                    </tr>
                    <tr>
                        <td>高尔夫球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>高尔夫球球员</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>球童</td>
                    </tr>
                    <tr>
                        <td>保龄球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>保龄球球员</td>
                    </tr>
                    <tr>
                        <td>桌球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>桌球球员</td>
                    </tr>
                    <tr>
                        <td>羽毛球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>羽毛球球员</td>
                    </tr>
                    <tr>
                        <td>游泳</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>游泳人员</td>
                    </tr>
                    <tr>
                        <td>射箭</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>射箭人员</td>
                    </tr>
                    <tr>
                        <td>网球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>网球球员</td>
                    </tr>
                    <tr>
                        <td>垒球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>垒球球员</td>
                    </tr>
                    <tr>
                        <td>溜冰</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>溜冰人员</td>
                    </tr>
                    <tr>
                        <td>射击</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>射击人员</td>
                    </tr>
                    <tr>
                        <td>民族体育活动（不含竞技性）</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>民族体育活动人员</td>
                    </tr>
                    <tr>
                        <td>举重</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>举重人员</td>
                    </tr>
                    <tr>
                        <td>篮球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>篮球球员</td>
                    </tr>
                    <tr>
                        <td>排球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>排球球员</td>
                    </tr>
                    <tr>
                        <td>棒球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>棒球球员</td>
                    </tr>
                    <tr>
                        <td>田径</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>参赛人员</td>
                    </tr>
                    <tr>
                        <td>体操</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>体操人员</td>
                    </tr>
                    <tr>
                        <td>滑水</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td>帆船</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>驾乘人员</td>
                    </tr>
                    <tr>
                        <td>划船</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>驾乘人员</td>
                    </tr>
                    <tr>
                        <td>泛舟</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>驾乘人员</td>
                    </tr>
                    <tr>
                        <td>巧固球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>巧固球球员</td>
                    </tr>
                    <tr>
                        <td>手球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>手球球员</td>
                    </tr>
                    <tr>
                        <td>风浪板</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>驾乘人员</td>
                    </tr>
                    <tr>
                        <td>水上摩托艇</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>驾乘人员</td>
                    </tr>
                    <tr>
                        <td>足球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>足球球员</td>
                    </tr>
                    <tr>
                        <td>曲棍球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td>橄榄球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td>乒乓球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>乒乓球球员</td>
                    </tr>
                    <tr>
                        <td>击剑</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td>击剑运动员</td>
                    </tr>
                    <tr>
                        <td>冰上曲棍球</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td>摔跤</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td>柔道</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td>空手道</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td>武术</td>
                        <td>教练</td>
                    </tr>
                    <tr>
                        <td>拳击</td>
                        <td>教练</td>
                    </tr>
                </tbody></table>
            </div>
        </div>
    </div>
    <div class="confirm" @click="closeOccupation"><span class="iconfont">&#xe612;</span></div>
</div>
</template>
<script>
export default {
    name: 'popoccupation',
    data() {
        return {
        }
    },
    methods: {
        closeOccupation() {
            this.$emit('closeOccupation')
        },
    }
}
</script>
<style scoped>
@import url('../../../assets/styles/public/public-pop');
.modal-content {
    background-color: #fff;
    border-radius: 0 0 10px 10px;
    margin-left: 0;
    margin-right: 0;
    padding: 20px 24px 10px;
    -webkit-overflow-scrolling: touch;
}
.blyw-table {
    width: 100%;
    text-align: left;
    border-radius: 5px;
    border: 1px solid #999
}
.blyw-table th, .blyw-table td {
    padding: 0.3rem 0.2rem;
    border: 1px solid #999
}
</style>